- name: Install Podman related packages
  apt:
    name:
      - podman
      - podman-docker
      - podman-compose
      - podman-systemd
    state: present

- name: Enable and start podman socket
  systemd:
    name: podman.socket
    enabled: yes
    state: started

